### ISSUE TITLE
SystemCheckError: System check identified some issues

### ISSUE THREAD

**Issue by nbosc** [phi-grib/DjangoAPI#2]
I recently had to reinstall RDTExtractorWeb conda environment. When running the server I get:
```
(RDTExtractorWeb) C02XJ285JGH6:RDTExtractorWeb nbosc$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/nbosc/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/nbosc/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nbosc/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/nbosc/anaconda3/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/nbosc/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 436, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (corsheaders.E013) Origin 'http//:localhost:4200' in CORS_ORIGIN_WHITELIST is missing  scheme or netloc
	HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).
?: (corsheaders.E013) Origin 'http//:localhost:8000' in CORS_ORIGIN_WHITELIST is missing  scheme or netloc
	HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).

System check identified 2 issues (0 silenced).
```

**Comment by nbosc** [comment]
That was a bit hard to identify but I've found the problem.
Change 'http//:' to 'http://' in CORS_ORIGIN_WHITELIST
